### ISSUE TITLE
Sky Sport Italia

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#113]
# Request
Sky Sport Italia
`https://sport.sky.it/formula-1`
`https://sport.sky.it/motogp`
`https://sport.sky.it/calcio`
`https://sport.sky.it/nba`
`https://sport.sky.it/tennis`

For other channels maybe you can learn more, I got references from this web site
`https://tvepg.eu/en/italy`

**Comment by K-vanc** [comment]
There is no epg data on the links you have provided

When i choose "programmi", it redirects me to guidatv.sky.it which is already available in Italy folder with those channels..

Thanks, I dont want to learn more from tvepg.eu

**Comment by K-vanc** [comment]
tvepg.eu siteconfig, I've already done long time ago but it is not very functional since it requires personal cookie file that cannot be automated by me so each user has to open browser, visit website, pass from I-am-human-verification then has to capture cookie and edit siteconfig to paste that cookie but also cookies have expiry dates so this things have to be done periodically by each user. This is very complicated for many users since sometimes I am receiving mails such as;

"I copied tempest.php on desktop, 
double clicked, 
nothing happened, 
right clicked,
choosed run as admin;
nothing happened,
your file is not working.."

So I dont want to receive another tons of not working notification for people dont know what is cookie and where it can be found etc. etc.
