### ISSUE TITLE
Request for DYN.SPORT site config

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#116]
Possible to get a siteconfig for Dyn.Sport?

```https://www.dyn.sport/aktion/willkommen?gclsrc=aw.ds&gad_source=1&gclid=*```

thanks

**Comment by K-vanc** [comment]
Hi;

if there is a visible table for epg data in the website, yes it is possible to get a siteconfig but if someone only pastes url of a website and expect to receive a siteconfig for it, answer is no.

I dont see any epg on the url that you pasted. Do you see any page/table there?

**Comment by cyb3rgh05t** [comment]
Hi , thanks for replying

only shedule for dynsport i found is 

https://www.thesportsdb.com/channel/2578-DYN-Schedule

is it that what you need?

**Comment by K-vanc** [comment]
this is close to what I need but also not good. That website is just showing a few event with multiple timezones, I checked a bit but there are clashing shows with same start time since it is not an actual tv schedule and cannot be scrapped because every clashing show will increament date by 1 day. 

I also check other Germany and some Multi Nation sources which are providing data for DE but this channel is not exist in anywhere. Maybe it is too early for it to get a proper schedule.

just look around and raise request again if you can find a proper source such as below examples;

https://waidwerk.tv/epg/

https://www.dazn.com/de-DE/news/fußball/dazn-1-2-programm-linearen-tv-kanaele/10gf70zpt9mxe12fs2zga8s4nq

**Comment by cyb3rgh05t** [comment]
alright thanks
