### ISSUE TITLE
404 Response

### ISSUE THREAD

**Issue by UzunMuhalefet** [K-vanc/Tempest-EPG-Generator#118]
## Issue Type

Please choose your issue type

* [X] Request

Hi again,

I found a strange case. I wanted to retrieve kepeztv.az data. But the main page that holds EPG data is giving 404 response all the time. As far as I understand, if the system sees a 404 response does not take the response itself. (I tried with some 404 pages as well)

Page URL:
http://www.kepeztv.az/

Attachments:

![Screenshot 2024-04-29 at 13 17 46](https://github.com/K-vanc/Tempest-EPG-Generator/assets/80906858/c17ded60-dcd5-41ff-ac69-df6b6bcc9fbf)
![Screenshot 2024-04-29 at 13 23 27](https://github.com/K-vanc/Tempest-EPG-Generator/assets/80906858/8c0b0326-6805-4a46-931c-140a474a80c0)

Is there any way to handle this?

**Comment by K-vanc** [comment]
and yes, this is the thing that I waited to see by someone for looong time 😄 ;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/4bd7a443-5da9-426d-97ac-ac6fc95e41ef)

**Comment by K-vanc** [comment]
For this one, I will keep you a bit more on hold till I release v1.7.0.0. I think the method that they used, could be a good way of blocking some web scrappers so made it an option as "Proceed-on-Error" for new version. Only enabling that option, will do the trick but need to test it's effects more since it may cause some other problem when used unnecessarily. Also still have a few more things to do for v1.7 

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/db61c8c8-8e97-4ec0-987e-34b777cf317d)

**Comment by K-vanc** [comment]
Hi;

Kepez added into Azerbaijan folder. You may use after updating Tempest into version 1.7.0.0
