### ISSUE TITLE
Tivo giving 500 errors

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#122]
I'm using the latest version of tempest.php and I started seeing 500 errors in the log for all the USA tivo channels.

**Comment by K-vanc** [comment]
Hi @stuckinthe ;

http 500 error means internal server error. This is not related with Tempest or siteconfig but related with website as it cannot reply your request due to some issue on server side.

if you google error codes, you can easily find this;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/63f5eddf-a2f0-4ddc-bf0f-425da59808eb)

I randomly test some channels and it is working;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/b4a9f038-d233-4323-9dcd-1b02bc9f08c3)

So probably, the data which you have requested is corrupted. This can be related with data of some channels with different regions or  data of some further dates as I requested only 1 day data.

There is nothing to do except waiting website to fix that issue or corrupted portion passes. I know another websites on my daily grab routine as 2-3 times a year same issue happening. They both using json response and some wrong entry is breaking json structure. When server cannot parse json, it stops responding. It is not working for 2 days and when corrupted data part passes, server starts working again
