### ISSUE TITLE
[Albania] tring.al

### ISSUE THREAD

**Issue by febiferdiansyah** [K-vanc/Tempest-EPG-Generator#127]
Can you update the config for this site address, because it doesn't work anymore.. thanks

**Comment by K-vanc** [comment]
it is working but usually website blocking ip adresses. Since you don't think a log file or screenshot of any error message related to url error code(if any) is not needed, this is all I can say. Use a vpn and it will be fine

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/cd5274ab-ea85-410b-a28f-d49bf2f846f8)
