### ISSUE TITLE
its possible add Tubi guide ?

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#130]
`https://tubitv.com/live`

i dont found this one in any of the listings from usa. honestly.  I Tought its on roku one but its not there.

theres some exclusive channels from tubi , warner bross channels those are like 8 , maybe there its some more exclusive from tubi.

thanks

**Comment by K-vanc** [comment]
I will take a look when i am back from vacation

**Comment by Toei79** [comment]
like always thank you so much  :)

**Comment by K-vanc** [comment]
hi,

unfortunately, you have to wait for my to-do-with-vpn list

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/e1240149-ec3e-4525-a7ad-818f5423f509)

**Comment by Toei79** [comment]
Understand  thanks

**Comment by K-vanc** [comment]
Are you sure there is a live tab for tubi? I am able get behind geo-blocking but there is no such tab as "live" or channels/epg. Are it is behind a login?

**Comment by Toei79** [comment]
![Screenshot_20240626-070608_Chrome](https://github.com/K-vanc/Tempest-EPG-Generator/assets/79808610/a1e2fabf-4572-48d5-840d-d18d778e247b)
This its what i see here

**Comment by K-vanc** [comment]
hmm so it is geo-blocked.. I thought maybe I can do it without VPN and did some progress but it is not opening such tab or displaying something similar. I can only see movies and series

**Comment by Toei79** [comment]
understand never tough was so restrictive

**Comment by K-vanc** [comment]
Hi;

Yesterday I had some time to check. I have good and bad news. Good part is epg grabbing is working and bad is channel creation is not working atm. They have very high level of security to protect their stream urls and unfortunately channel id/names are only provided with stream urls.. I managed to hack it to get a channel list but making it dynamic and available for all users are not an easy job. I need to spend hours/days to fully resolve their protection and I don't have time for it. So I will not upload into repo but you can use from here after renaming file extension(delete last .txt part from both files) and also DONT USE CHANNEL CREATION because it is not working and give you empty list. Also valid US Ip adress is required

[[ENC]tubitv.com_0.siteconfig.php.txt](https://github.com/user-attachments/files/16114892/ENC.tubitv.com_0.siteconfig.php.txt)

[[ENC]tubitv.com_0.channel.xml.txt](https://github.com/user-attachments/files/16114893/ENC.tubitv.com_0.channel.xml.txt)

**Comment by Toei79** [comment]
understand, wow crazy and they are a free service , but thanks man i give a try

**Comment by Toei79** [comment]
> Hi;
> 
> Yesterday I had some time to check. I have good and bad news. Good part is epg grabbing is working and bad is channel creation is not working atm. They have very high level of security to protect their stream urls and unfortunately channel id/names are only provided with stream urls.. I managed to hack it to get a channel list but making it dynamic and available for all users are not an easy job. I need to spend hours/days to fully resolve their protection and I don't have time for it. So I will not upload into repo but you can use from here after renaming file extension(delete last .txt part from both files) and also DONT USE CHANNEL CREATION because it is not working and give you empty list. Also valid US Ip adress is required
> 
> [[ENC]tubitv.com_0.siteconfig.php.txt](https://github.com/user-attachments/files/16114892/ENC.tubitv.com_0.siteconfig.php.txt)
> 
> [[ENC]tubitv.com_0.channel.xml.txt](https://github.com/user-attachments/files/16114893/ENC.tubitv.com_0.channel.xml.txt)

change extensions to normal and permissions for both files  but i get this

Siteconfig.php not found...
Channel skipped...

**Comment by K-vanc** [comment]
Check name of siteconfig and channel.xml files. When downloading attachments, github renaming them as

ENC.tubitv

But it should be 

[ENC].tubitv...

**Comment by Toei79** [comment]
i did that i guess for try

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/79808610/24593530-4cb6-4e20-9e98-18838d0392fb)
but nothing or i wrote it wrong

**Comment by Toei79** [comment]
ok i removed .

**Comment by K-vanc** [comment]
Enjoy and be careful about malwares 😀
