### ISSUE TITLE
[REQUEST] PLUTO TV EPG for different countries

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#138]
Hi,

is it possible to add Pluto TV EPG for different countries like Germany France UK Portugal Italy etc?

Thanks in advance

**Comment by Toei79** [comment]
guessing you using tivimate or other iptv player.  no matter what you gonnna get only 6 hours of epg. thats limitation there.

so if you get thought tivimate you get epg same source.

**Comment by K-vanc** [comment]
Hi guys, 

I am able get data for almost for 1,5 days. I didnt understand your part for 6 hours epg limit.

Anyway, urls are same for all countries and you need to use different vpn/proxy for both channel creation and epg grabbing so i am trying to make it more user friendly before publishing because it will be difficult for users to use. Probably you need to prepare seperate configuration for each country and have to set different vpn location prior to each epg/channel run

**Comment by K-vanc** [comment]
Ok, added into Multi Nation folder

Just keep in mind that;

* it is very dependent on your ip adress location
* for different countries, you need to use different vpn locations to channel create
* since urls are same for all countries, correct location shall be set for epg grabbing as well
* after new release of Tempest, I will update this siteconfig again for some changes but currently everything is ok
* AS IMPORTANT NOTE, it will not work if it does not like your ip adress. I tried several ip adress for same locations and some worked fine at all while some always gave empty page so if that happen, I cannot help, you have to change your ip adress

**Comment by Toei79** [comment]
Theres a limit of 6 hours on one know epg provider from pluto also in pluto

Cool you get 1 day 5 hpurs

**Comment by K-vanc** [comment]
> Theres a limit of 6 hours on one know epg provider from pluto also in pluto
> 
> Cool you get 1 day 5 hpurs

Well, you know, they cannot limit me 😄

**Comment by cyb3rgh05t** [comment]
great thanks a lot
