### ISSUE TITLE
digea.gr issues

### ISSUE THREAD

**Issue by backyard-bbq** [K-vanc/Tempest-EPG-Generator#139]
I am having issues with digea.gr the gr version as I get a timeout error. I went to the website and I see the epg data is available.

I just did a git pull to make sure I wasn't missing an update. I have the latest digea.gr files.

**Comment by K-vanc** [comment]
Hi,

I checked but it is working fine here

![Screenshot_20240712_140658_Chrome.jpg](https://github.com/user-attachments/assets/8171d6a7-c612-414e-9f6d-420963d00e30)

Since you didnt attach a log/screenshot/copy-paste of error, timeout should be related with your internet. Check your dns settings and try to visit website from the same machine where u r using Tempest. Also from Configuration settings, increase time-out value to something higher such as 30 and try again. Probably it is related with your network because website response time is very low

**Comment by K-vanc** [comment]
Hi, closing the issue as no response
