### ISSUE TITLE
This is a very good project, but

### ISSUE THREAD

**Issue by Yumega** [K-vanc/Tempest-EPG-Generator#140]
it has installed but It's very complicated, Read the TempestWIKI.pdf, don't know how to use

Tempest will generate its file structure on the first run into the folder that "tempest.php" stored, but my system didn't generate its file structure.

![image](https://github.com/user-attachments/assets/d687e329-d332-448e-8ad5-e7bf5cabe5f6)

**Comment by K-vanc** [comment]
Hi and thanks for using Tempest.

Tempest is the most advanced programmable epg generator so it is not designed to be (so) simple but if you don't have any plan for making your own siteconfigs, then remaining part is pretty easy and straight forward by copying needed siteconfigs files, creating a configuration file with the channels you want and grabbing EPG.

Based on your second screenshot, I can tell you that you have permission issue with your Unix. PHP cannot edit anything belongs to "root" user if you didnt specifically set it so(just never do it as it is extreamly dangerous).

So what you need to do is finding your servers user name and set it to entire folder of your document-root-folder. For example if you are using Nginx then default user:group name is "www-data" so you need to chown your folder directory accordingly;

Example(dont copy/paste if your user is different)

`sudo chown www-data:www-data -R /your/server/root/folder `

will change ownership of your directory and existing files to www-data user. Then you need to set permissions correctly. As shown on your photo "-rw-r--r--" part explains what permissions of your user/group/and others have on this file/folder. Basicly, first part -rw means root user has read/write permission
second -r part, group users have only read permission
last -r part, all other users have only read permission so of course Tempest cannot create its folder structure with these settings since as "Other users", it can only read the file. So to fix it, you need to chmod read-write-execute permissions as;

`sudo chmod 777 -R /your/server/root/folder `

777 means everyone can read-write and execute. This setting will work for all newbie Unix users but it is not the best so you can set something more suitable for you. And finally after all this settings, when you reload your browser, it all will work. 

By the way, you complained about Tempest is very complicated but nothing above I wrote is related with Tempest. All these are the settings of UNIX so as a Unix user, you need to learn what is permissions, how to set/change groups for new/existing users and how to change read-write-execute permissions. Technically I have no responsibility or duty to teach users how to set file/folders under Unix.  I just wanted to explain you what is so complicated 😄

**Comment by K-vanc** [comment]
I dont know how you installed others. For docker, environment set to nobody user and you don't need to set any other thing but usually people are trying to install with copy/paste composer files without knowing the meaning of parameters in that composer file then asking me as not working. Based on above fact, inside of that container cannot be root user if you wouldnt set parameters without knowing what are they..

Only thing you need to do is mounting your folder for docker setup but as far as I see, you are even trying to set a php-user.ini. If your main system is not Unix, just follow below header in README section;

How to install Tempest Docker image?
 
Otherwise, fix folder permissions of your mount folder then follow above header in README section


GENERAL NOTE:
We cannot expect codes to work by copy/pasting random docker installation settings and in case of failure to ask developer to help/fix it

**Comment by K-vanc** [comment]
nothing will change because problem is 

- PUID=1000
- PGID=1000

You need to delete them and as i said, if your system is unix then first set proper ownership for mount folder before container build

**Comment by K-vanc** [comment]
* delete your container
* sudo chown nobody:nogroup -R /opt/tvepg/
* sudo chmod 777 -R /opt/tvepg/

after that use below composer;

`services:
tvepg:
ports:
- 7880:8095
container_name: tvepg
environment:
- TZ=Asia/Shanghai
volumes:
- /opt/tvepg/:/var/www/html/tempest_config/
image: kvanc/tempest_epg`

**Comment by K-vanc** [comment]
you can follow instructions for channel copy/paste, configuration preparation and running

https://github.com/K-vanc/Tempest-EPG-Generator/tree/main/Siteconfigs/0_How%20to%20use

**Comment by K-vanc** [comment]
> wow, it works now, amazing
> 
> now I need creat a epg for https://raw.githubusercontent.com/Yumega/max/master/media/IPTV/Home.m3u
> 
> how to do?

I dont know, Tempest will create xml file which contains epg data. You need to upload that generated file into your iptv player and map the channels. If you are using Kodi, then m3u  tvg-id="" value should match with channel id in generated xml file or something like this. I dont use kodi for epg so you may google it how. Many modern iptv players are supporting channel mapping from their user interface in these days

**Comment by K-vanc** [comment]
It will generate an epg file with xml extension and since docker container build with an web server(Nginx), generated xml file will be reachable through ip adress.

same as you call tempest.php file, you can modify your url to reach that epg file. If you are calling tempest.php with;

http://localhost:8095/tempest.php

below url will go to your epg file;

http://localhost:8095/tempest_config/epg/YOURFILE.xml

Don't you anything about UNIX or Webservers or php or samething similar?? I cannot explain/show you everything here. Tempest is running so I am done with you

**Comment by K-vanc** [comment]
yes, there is a mistake since the beginning of this issue topic....

Now you are using a browser which is not properly rendering javascript.

![image](https://github.com/user-attachments/assets/a3edd93e-05c3-4702-ae12-a18d512f13d5)

Really, I am dealing with your questions for almost 2 hours and all was your side issues including this.. SO if it is alright with you, I have other important things to do..
