### ISSUE TITLE
Fix siteconfig time format

### ISSUE THREAD

**Issue by NHKRoku** [K-vanc/Tempest-EPG-Generator#142]
Hi
Recently,I have build a new siteconfig for new services,but I have a trouble with time format,It always notice that time conversation error but I don't know why it wrong,so can you check my time format please.
Following is my siteconfig and log I have debug
[12_0.siteconfig.txt](https://github.com/user-attachments/files/16367656/12_0.siteconfig.txt)
[Tempest_debugger.txt](https://github.com/user-attachments/files/16367658/Tempest_debugger.txt)
Thanks for helping.

**Comment by K-vanc** [comment]
Hi, It is good to see you are learning how to make siteconfig.

I've checked your siteconfig, it is a good one for starting. Now I will explain some of your mistakes and why it is giving that error. I copy/pasted your debugged data into my regex checker and tested your show pattern. Show pattern is used for capturing show blocks which may contain start/stop/title/desc and/or etc. that belongs to each show and all other element patterns check inside of these blocks but your show block capturing only show id 😄 so there is no other data to capture inside. Green ones are what you are capturing as show block;

![image](https://github.com/user-attachments/assets/f3ada7e0-5f3f-42ee-b6fa-9d3feda8c0e1)

and same result displayed in your debug file;

![image](https://github.com/user-attachments/assets/e05fd95b-1f56-45da-adf6-e73041de4214)

Since we know the problem now, we should fix it  by changing show pattern something like this;

`For show => ({"id".*?})`

now lets check how it is looking;

![image](https://github.com/user-attachments/assets/ce1b79b9-bce2-4727-b966-547df590dbeb)

you can see the difference on green blocks. Now each block contains start/stop times(in 2 diff format), titles, desc and some other things. Now your start/stop patterns will capture. Just as a suggestion, there are also java timestamps available for start/stop times. Whenever unix/java timestamps available, I always prefer to use them since they contain also date information inside;

"epochSt":1721843400000,"epochEt":1721844300000

these 13-digits numbers are java timestamp and if they are 10-digits long, it means they are unix timestamp. For capturing them, you need to use below patterns;

`For start => "epochSt":(\d+)
 For start format => java
 For stop => "epochEt":(\d+)
 For stopformat => java`

and last thing about timestamps is you need to keep in your mind that they are always UTC timezone(+0000) so if you are using timestamps then your timezone shall be set to UTC;

`'timezone' => 'UTC',`

I am not giving you ready siteconfig in order not to kill all the fun so good luck 😄
