### ISSUE TITLE
Tivo says no shows grabbed for all of channels in my config

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#145]
I am receiving no shows grabbed for the tivo config file. I used the old tempest and I used the new tempest. With the new, I made the changes and corrected the command line. I have tried on multiple  computers and I tried a fresh config file. I also tried the CBS OTA and the spectrum and frontier figuring those would have guide data.

**Comment by K-vanc** [comment]
Hi

Old tempest??

New tempest??

Which channel??

Of which line up??

I see no problem..

![Screenshot_20240810_222648_Chrome.jpg](https://github.com/user-attachments/assets/14857dab-3919-47ab-91e9-befc135f9a27)

I cannot help more than this with your strange feedbacks

Thanks

**Comment by stuckinthe** [comment]
`I also tried the CBS OTA and the spectrum and frontier figuring those would have guide data.`

You tried the one I gave you in my original post (CBS OTA) and you are receiving data and I am not so it must be my issue.

I used the version of tempest that needed the following command:

php tempest.php engine=Generate tempconfig=tempest.config.xml  

and then the one that needs

php tempest.php --epg config=tempest

I won't bother you anymore. I wasn't being snotty or demanding.

**Comment by K-vanc** [comment]
Hi, 

you are not bothering me but issues like simply saying "not working" is not helping me to understand problem. There is a template for new issues which you can write your tempest version, os details etc. so instead of "old tempest" or "new tempest" words, I can understand which version you are using. I made 24 releases up to now so how do you expect me to know which one is old tempest? 

Again what you mention as CBS OTA or frontier or whatsoever makes no sense to me because I am not using any of those channels. If you attach a tempest log file, instead of all these statements, i can easily see your tempest/os version and what channel you are trying to grab.

You mentioned that you have tried on several pcs but not mentioned if they are on the same networks. Just try to visit website form that network to see you are able to display website. Also you didnt mention if you updated siteconfig or not. As I wrote in several places, [ENC][EX] siteconfigs are dead as of 03-08-2024 if you havent updated it yet. So it will never work

**Comment by K-vanc** [comment]
Just an extra, I dont know why people started that comparison in these days as old tempest/new tempest. There is only 1 tempest as latest. Changes are written on release tab but grabbing engine is not changing (yet) so a siteconfig which works on an old release, will always continue to work on a newer release but this does not apply reverse.
