### ISSUE TITLE
[QUESTION] SKY.de siteconfig

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#146]
Tempest Version Docker rv2.0.0.0-2407201314
Ubuntu 20.04

Hi,

i realized that ```[ENC][EX]sky.de_0.channel``` vs ```[ENC][EX]web.magentatv.de_0.channel``` that all sky cinema channels (action, classics, etc) dont have any epg in the sky config while in magenta config they have epg. is there a problem with the sky config?

**Comment by K-vanc** [comment]
Hi

Several channel ids changed in sky.de. if you create fresh channel list then replace newly generated channels with old ones, you will see it is grabbing..

This process is not special for sky.de and should be repeated any siteconfig periodically since it is normal for websites that they can change anytime their own assigned channel ids as they want.

![Screenshot_20240810_223243_Chrome.jpg](https://github.com/user-attachments/assets/187ca46d-5cb8-4f3f-94b5-5c3b57eb0de1)



Note: Grabbed in index-only mode to fast proofing. Normal grabbing takes longer time

**Comment by cyb3rgh05t** [comment]
hmm what exactly do i need to do?

**Comment by K-vanc** [comment]
i already wrote what you need to do above.

* Channel create by using sky.de
* Open your configuration file and delete sky.de channels
* Choose sky.de siteconfig from channel selector so newly created channel list will be displayed
* Select the channels and click right button so they will be sent to selected channels box
* Click register
* Click save
* Run epg engine for this configuration

I believe i didnt miss a step
