### ISSUE TITLE
Siteconfig request

### ISSUE THREAD

**Issue by NHKRoku** [K-vanc/Tempest-EPG-Generator#165]
Hi
I'm back here to request a new siteconfig
I see that you've created a VTVcab'siteconfig,but it only available in 4 days
And on that siteconfig have 9 channels can be used in this request
You can find that on link here:https://vtv.vn/lich-phat-song-ngay-20-thang-10-nam-2024.htm
<Fun fact:There's still have another link to EPG but it run in HTML like this:https://vtv.vn/ajax-schedule-live-video-page-3.htm
Thanks for your work!

**Comment by K-vanc** [comment]
For the first one, I dont really any benefit of adding this siteconfig since these channels are available in other sources. I checked the website and shows has no channel identifier so it has to listed. I can be this assignment but when I click for tomorrow, channel number is dropping to 7 and day after tomorrow, it becaming 5 channels. With linear alignment, you will get wrong channel shows on multiple day requests and there is noway for me to know which channel will be available on next day request so I have to limit it with 1 day only grabbing.. As I said, it is just too much work for almost nothing.. 

I will do it if I have lots of free time and bored so much of doing nothing..

For the second one, it can be called by single channel with some identifier(i think so, didnt check all) so if possible, I will add it

**Comment by K-vanc** [comment]
Siteconfig for 2nd url added into Vietnam folder
