### ISSUE TITLE
TV.nu not working anymore

### ISSUE THREAD

**Issue by Jimpan81** [K-vanc/Tempest-EPG-Generator#182]
Tv.nu not working anymore, was working fine before and allente still works so must be some issue with tv.nu site.

Example:

78/78) Site: [ENC]tv.nu_0
Channel id: 30264
Xmltv id: SkyShowtime 2
No show grabbed in 0.14 seconds
Request Error(url1): The requested URL returned error: 403
Request Error(url1): The requested URL returned error: 403

edit
looks my ip got banned :(
tv.nu from Chrome webbrowser:
Error 1006 Ray ID: 8f276477ce1b95fc • 2024-12-15 15:16:01 UTC
Access denied
What happened?
The owner of this website (www.tv.nu) has banned your IP address (123.123.123.123).

Works with vpn now but how to prevent this from happen again @K-vanc ? I only grab once a day

**Comment by K-vanc** [comment]
Siteconfig works fine here and html 403 error code means "Forbidden" by website/server.

There is nothing you can do except using vpn/proxy till they unban(usually ban is temporarily for a while) you. Also if you have dynamic external ip, you can reboot your router so a fresh(not blacklisted) ip adress will be assigned. Website is not using any special cookie or cloudflare etc so probably they noticed you by routine activities and page visit speed which called flood control. You can add some delay from configuration file to channel, index and detail options so it will grab slower(will wait among next operation) but will also look like more human so will be harder to notice for website. It is very simple to identify a scrapper by page visit speed since you cannot visit 60 pages in 20 seconds from browser

**Comment by Jimpan81** [comment]
@K-vanc 
grabber gets stuck on (11/78) Site: [ENC]tv.nu_0 Channel id: 70 Xmltv id: Kanal 11
So 1-10 ok and on 11 it stucks and doesn`t get by. 

Can you check if you can grab hole tv.nu for one day?

OK:
10/78) Site: [ENC]tv.nu_0
Channel id: 68
Xmltv id: TV10
56 shows grabbed in 74.67 seconds

NOT OK:
(11/78) Site: [ENC]tv.nu_0
Channel id: 70
Xmltv id: Kanal 11

**Comment by K-vanc** [comment]
My friend, I think first of all, you need to change your arguments. First you said siteconfig is not working and now telling grabber gets stuck.. It is not problem of siteconfig or Tempest but it is problem of your network/pc as red flagged by website. Normally, you shouldn't even raise an issue here for this since this is not a thing related with my software or something that I can help you..

Grabber is not getting stuck but website is cutting your connection after 10 channels without sending close-out message then Tempest is waiting for curl time-out. If you wait long enough, you will see timeout messages. I attached log which is generated by rv2.2.1.0 maybe it helps since nobody mentions such details because when you type "NOT WORKING", I am able to see all your system information and tempest version etc..

[Tempest_log.txt](https://github.com/user-attachments/files/18144979/Tempest_log.txt)

Anyway, as i said, there is nothing i can help for a banned ip adress from 1 website. Possible solutions for you;

* Split your channels into groups with max 10 and add channel from another siteconfig so if you are not using synchrotron, it will give a breath to website
* add some different free proxies to each 10 channels group from configuration file
* prepare several and smaller configurations to work with different vpn/proxy and merge them with xmlmerger if all grabs

I checked website now and they changed some urls while also ours are still actively working. I will prepare rev1 for this siteconfig that maybe they will not block you this time. I will write here when I upload rev1. If it also does not work, you can try below options as last resort;

* Ask website to unban you with an apologizing email
* Change your ISP for  changing your digital footprint

**Comment by K-vanc** [comment]
I attached rev1 in Sweden folder. It uses different url with completely different channel ids so you need to change everything. Also I dont know why but I acted very proactively to modify rev0 also with some http2 headers that I believe(actually sure) it will have 0 impact on your situation but you may try also that one

**Comment by Jimpan81** [comment]
Thanks!
Just some miss understanding. When i wrote not working , it was not working for me and i had not changed anything for months. Later  i noticed the ip-ban. After that i started with vpn and i could only grab a small amount of channels.

Big thanks for you trying to help.

Anyway , just tryed the new tv.nu files but did not help **me**   First channels grabs without problem after that is stuck again  / or "kicked out" Been waiting 2h no and it does not recover.

I guess i`ll have to use some other site. Allente grabs the channels blazing fast but don't have all the info Tv.nu has.

Allatvkanaler looks like a better option but i cant get the grabber to work. Error on all channels "Start-time conversion error found on block 1..."  

Site: allatvkanaler.se_0
Channel id: axess-tv
Xmltv id: Axess TV
Start-time conversion error found on block 1...
No show grabbed in 4.44 seconds


Any idea what i'm missing?

**Comment by K-vanc** [comment]
I dont know, i am away from pc but start time error shouldnt be something hard to fix. I can check tomorrow

Btw, can you write your Tempest and php version?

**Comment by Jimpan81** [comment]
rv2.2.1.0-2412111148 and PHP 7.4
I was finaly able to grab one whole day with all channels from tv.nu. 
I will try to grab some more days tomorrow  and let you know how it goes

**Comment by K-vanc** [comment]
I added new version of allatvkanaler. It was not a simple start time issue but was complete rewrite

**Comment by Jimpan81** [comment]
@K-vanc tv.nu blocked my vpn ip also after a few days. So looks like i have to start using some other site config. Thanks anyway

**Comment by K-vanc** [comment]
Hi, it is better to give them a break. Remember that ip adress is not the only data for a server to identify you. They can see your mac adress, geolocation and many other things. If they are specifically tyring to hunt you down, this is not a war you can win.
