### ISSUE TITLE
[Feature Request] Docker Updates

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#184]
Hi,

will it be possible to configure the docker container to be also updated to the latest updates?

because as of now everytime the container gets redeployed it reverts to the 1.6 version and you need to manually update the container over GUI. 

and yes if you forget to do this then the crons would not work due to the version 1.6 and in 2.0 all cli commands changed.

Can you follow me?

thanks

**Comment by K-vanc** [comment]
Hi, 

Actually, i have no plan to update docker container till next major update of php or nginx which both versions in container are still very close to latest versions. Building new image on each update time taking process(for each different cpu architecht etc.) and need to be tested since alpine os has minor difference which may cause problems on functionality. I coded tempest updater just for this purpose to update latest with one click or one simple code line execution without rebuilding of container.

Btw, may i ask why you need to redeploy container everytime? If you want to close container for gaining memory when you dont to use it, simply you can stop it start again when you want to use. This way, all your settings will remain same including tempest updates;

`docker start <container_id> 

docker stop <container_id>`

This is the way of stopping/starting unused containers instead of destroying and reinstalling everytime

**Comment by cyb3rgh05t** [comment]
thanks for the information.. it seems then something is not configured at my because it does the same on restarting the contianer, i alsways need to update tempest again.

but no worries, was just a question

**Comment by K-vanc** [comment]
You mean your container is being reset to original state after reboot? 

Anyway, I added docker container update to my to-do list, maybe it can be an opportunity for me to tweak server performance. Let's see when I can find some free time to work on it

**Comment by cyb3rgh05t** [comment]
yes on reboot it goes to 1.6 version again, and if i miss updating it will not do the cronjobs

**Comment by K-vanc** [comment]
i will publish new docker image soon, it will have auto update script on container startup

**Comment by K-vanc** [comment]
Hi @cyb3rgh05t 

New docker image released

**Comment by cyb3rgh05t** [comment]
thanks bro :)

**Comment by K-vanc** [comment]
welcome, btw I am also not an expert on docker but it seems it is normal behaviour of docker that container resets itself on each start-up so nothing is wrong with your setup. Containers are using a temporary file system which will be deleted on container shut-down. There is no way to save its progress.

**Comment by cyb3rgh05t** [comment]
got it thanks again
