### ISSUE TITLE
Enable Duplicate Channel Id Remover for ENC files.

### ISSUE THREAD

**Issue by amjiddader** [K-vanc/Tempest-EPG-Generator#2]
Hello I used EPG as my provider does not have EPG.

But issue is while Generating EPG.
I tried open file (un-encryped) and i checked below 2 options as it had 12 same channels and it worked perfectly.
>Enable Duplicate Channel Id Remover : 
>Enable Duplicate Channel Name Remover : 

While on an encrypted file i saw 30+ Duplicate IDs and Channels.
I have to manually rename ids and sometimes it does not work.

As we can not edit encrypted config files. 
So will you please consider to add default id and channel remover for duplicate?
>Enable Duplicate Channel Id Remover : 
>Enable Duplicate Channel Name Remover : 

Or allow us to at least edit these 2 options.

Thanks

**Comment by K-vanc** [comment]
Hi. Could you please mention for which siteconfig, you need duplicate remover? Usually if it is necessary, I am already enabling 1 of these options in locked siteconfig. 

For other cases, it may not be real duplicates same like USA providers. Usually you may see lots of same named channel in USA providers but they have different ids and/or logos which have slight changes due to local brodcast difference. So I cannot enable duplicate remover on 1 of these siteconfigs since another user may need local variant of that channel. Also sometimes channel ids may be same but it may be used on different url by subpage variable. Most of the time your manual correction is not needed and may result failure on grabbing. 

For XMLTV standard , you only need to manually correct xmltv_ids if they are dublicated and they will be highligted as red by Tempest and you will not be allowed to save your configuration file without changing them.

**Comment by K-vanc** [comment]
Anyway, I couldnt get any feedback from you but acted proactively and added 2 remover options to new release v1.4.2. So you can use these options on Channel Generator section for locked siteconfigs. I am closing the issue.

**Comment by amjiddader** [comment]
Thanks, I was away just checked,

For tvguide foxtel, in SLING_NEWYORK 2 cahannels are same.
for TATASKY INDIA 9 channels are same .

I understand sometimes same channels are for multi region's or multi-language That is fine anyone who need multi-language channels they can disabel CHANNELREMOVER and manually check channels.

I need this for myself on KODI on PC and tivi app on android.
Thanks for 1.4.2 - I will update right way,
