### ISSUE TITLE
[Question] Is it possible to set path for xml generated?

### ISSUE THREAD

**Issue by hemantgogia09** [K-vanc/Tempest-EPG-Generator#22]
Hi, I want to generate the xml under a folder instead next to the php file. Is it possible? thanks

**Comment by K-vanc** [comment]
Hi and thanks for using Tempest.

Generated xml file path is fixed since php (as creator of file) has different access and read/write permissions on Windows and Linux distros. Setting it as user-defined, probably will cause several problems on different users because possible folder structures and access rights are unpredictible. But you can still copy or cut the generated file into your target directory after generation done.

I think you are asking this for Crontab or Windows Scheduled Tasks operations. In both cases, you can add a new line into your .sh or .bat file for copying or moving to your target directory. For linux os, add below lines after tempest run cli command

<
sudo cp -r /path/of/xmlfile/Guide.xml /your/target/path
>

And for Windows;

<
copy C:\path\of\xmlfile\Guide.xml C:\your\target\path
>

Please note that in both cases, if you have any space in the path or file name, you need to wrap path strings with (")

**Comment by hemantgogia09** [comment]
yeah that makes sense. Thanks for the reply
