### ISSUE TITLE
Getting 503 error from dstv source 

### ISSUE THREAD

**Issue by hemantgogia09** [K-vanc/Tempest-EPG-Generator#25]
Hi, any idea how we can resolve this issue? I have been getting 503 error from dstv source since yesterday.

![image (12)](https://user-images.githubusercontent.com/3593462/230563460-1a6cfe7c-09e5-4d8c-9f6c-ff46ee4ee916.png)

**Comment by K-vanc** [comment]
Hi. 503 error means service is unavailable from server side. It may be a temporary or permanent issue. When I visit their website, epg grid is also completely empty. There is nothing more to do currently except waiting them to fix problem. Was it working day before yesterday? 

Some time ago, they made some alternative website for epg but it was not covering many countries. I will have a look that one tomorrow. If it is working and have more coverage now, i can create a new siteconfig for it

**Comment by hemantgogia09** [comment]
yes it was working day before yesterday. That will be great if we have an alternate source thanks.

**Comment by K-vanc** [comment]
I added 2 new revisions of dstv siteconfig with new api. I still dont know rev0 will be activated back or not so currently I am not deleting it from repo. rev1 and rev2 is identical except keepindex option which speeds up grabbing if you will grab from only single dstv country. If you want to make a channel bouquet with multiple dstv countries then use rev2.

**Comment by hemantgogia09** [comment]
Thanks a lot @K-vanc will try it later.

**Comment by hemantgogia09** [comment]
Hi @K-vanc the source you provided worked fine i used rev1 and it works fine for me. However my partner who lives in different timezone is facing different kind of issue while generating the xml file. We use the same config files.

Here is the problem while generating the xml it proceeds going through channel by channel grabbing shows and then on `SS Rugby` it stops forever and the loader animation on browser tab also goes away. So it seems some error is there but there is no log on browser window. We checked few logs on php side and we only saw `408` written without any description. (which should be timeout error)

Any way we can enable extra logs from tempest.php side? Any other things that we might be missing that you can suggest ?

**Comment by K-vanc** [comment]
Hi @hemantgogia09 ;

I set dstv siteconfig's timezone with ##usertime## command. This makes time offset dynamic based on user's own time. I set it so because I remember as server was responding adjusted show times based on requester ip's local time. So you think it is fixed +03:00 ? It could be my bad since I am also in the same timezone as +03:00

Regarding other case, is this the channel you mentioned?

![image](https://user-images.githubusercontent.com/97025515/231135246-754f9876-92bc-4ce4-8d21-a03398b78c0d.png)

If yes, it is fine here. HTML 408 error is timeout by remote server which means it didnt give any response for a while and closed the connection. it may be temporary or permanent issue but in no case it will not stop Tempest's operation and it should proceed with next channel. If operation stops on same point(actually same duration), it is probably related with your php server's timeout. If you are using UNIX distro, did you check what i wrote on the down of main page?

>There is 1 very important setting needs to be done by UNIX users since UNIX OS is not allowing me to set this parameter from script side.
>For NGINX;

>fastcgi_read_timeout

>and for APACHE;

>TimeOut

>parameter which server default is 300(5 mins), needs to be set some higher value such as 1800(30 mins) or 3600(1 hour). Otherwise you may have a timeout during the process after 5 minutes of initialisation. These parameters may be set as below for NGINX;

>in /etc/nginx/nginx.conf file, set under http directive. It will look like;

>http {
>#.....
>fastcgi_read_timeout 1800;
>#..
>}

>and for APACHE; you need to change TimeOut value in your httpd.conf or vhost config file. New setting will be applied after server reload as below;
>for NGINX;

>sudo service php7.0-fpm reload ("php7.0-fpm" is the one I use so you have to modify it based on php version you use)
>sudo service nginx reload

>and for APACHE;

>sudo service apache2 reload
>or
>sudo systemctl reload apache2

>For Windows, I didnt see such setting or limitation. I think it is set to "no limit" by default for Windows.
 
You can also enable basic error reporting by finding below strings in tempest.php (there are 2);

error_reporting(0);

and replace with;

error_reporting(1);

and save but what is related with connection etc. will be already displayed by Tempest on screen.

**Comment by hemantgogia09** [comment]
Hi @K-vanc,

We are on windows where we are facing this bug. On my mac it works just fine as you said. 

And yeah for errors the code moves to next channel that is how it has been but for some reason in this case it just stops

> (13/18) Site: [ENC][EX][dstv.com](http://dstv.com/)_1
Channel id: 211
Xmltv id: SSRugby

This are the last lines of log while executing tempest.php from browser and it just stopped, usually when there is something happening on php side browser waits with loading icon in place of favicon in tab area right? but it just stops and there no loading icon there. We waited for 50 mins but there is no more logs printed in page after that.

I will try `error_reporting` approach and report back if i find anything

**Comment by K-vanc** [comment]
I am able to grab from Rugby channel both on Windows and linux but couldnt find that SSRugby.Can you mention it is generated from which country? You mentioned it is ok also on mac so probably there is something wrong with your server setup or configuration. Could you please reply below questions?

Your server name(apache, Xammp etc.)
Your php version
Your Tempest version(top right)
Did you manually edit your configuration file?
Did You tried again by removing that channel from your configuration file and re-adding ?

**Comment by K-vanc** [comment]
You are welcome but still you have a problem. There is no memory error on this siteconfig and I am able run on my raspberry pi 3b+ with default 128mb php memory setting. Problem is you are using wamp as server. I started to write Tempest on wamp server because it was very easy to run without any extra settings etc but when I reach details pages, i noticed Tempest was running slower and reaching high memory consuption values. I investigated deeply to understand why and found out it is multitasking ability and strange garbage collector design which is not allowing tempest to open some free memory but it was not possible to fix since wamp was coded like this then I switced to built-in php development server and all fixed. If you are happy with it just proceed but definetely you dont need more than 30mb memory for this siteconfig.

For time offset issue,  where your parents located and what they are grabbing as show time? Do you have any information that you can share?

**Comment by hemantgogia09** [comment]
> For time offset issue, where your partner located and what is grabbing as show time? Do you have any information that you can share?

No there is no issue regarding timezone. i just mentioned it in my original message because i thought it could have some kind of impact on the problem that we were facing. My partner generates xml he is in +2:00 timezone and the show time has +00:00 timezone always

> You are welcome but still you have a problem. There is no memory error on this siteconfig and I am able run on my raspberry pi 3b+ with default 128mb php memory setting. Problem is you are using wamp as server. I started to write Tempest on wamp server because it was very easy to run without any extra settings etc but when I reach details pages, i noticed Tempest was running slower and reaching high memory consuption values. I investigated deeply to understand why and found out it is multitasking ability and strange garbage collector design which is not allowing tempest to open some free memory but it was not possible to fix since wamp was coded like this then I switced to built-in php development server and all fixed. If you are happy with it just proceed but definetely you dont need more than 30mb memory for this siteconfig.

Interesting so that is the problem, we are planning to move this on a proper linux server soon so i would not care about this problem much.

**Comment by K-vanc** [comment]
No, absolutalely you will not face again after moving. I suspected when I compared my testing results on i7 windows pc with Wamp and rpi3 with Nginx which rpi3 results were much more better. So seems they still didnt fix that memory leakage issue. Anyway, good to hear no other problem
