### ISSUE TITLE
Siteconfig request for Taiwan

### ISSUE THREAD

**Issue by Wangliann** [K-vanc/Tempest-EPG-Generator#28]
Please create siteconfig for https://www.tbc.net.tw/Epg. 

This site epg is probably main reason I'm still using webgrab+.

Best regards.

**Comment by K-vanc** [comment]
Hi and thanks for using Tempest.

I am on last few days of my vacation and will take a look of your request when I am back.

**Comment by K-vanc** [comment]
hi again. Unfortunately, it doesn't like my company network ip but I was able to open website on my mobile with Taiwan VPN. So I have to make a you alittle bit more of waiting till I return back home today for my personel pc where I have VPN access

**Comment by Wangliann** [comment]
Thank you~！

**Comment by K-vanc** [comment]
it has been added into Taiwan folder. Please note that suitable ip adress required in order to access website due to geo-location. 

I normally share only full versions of siteconfigs which means all available elements are in capture mode but I made an exception for this since it has only category as additional detail page so below attached unofficial version(rename .txt as .php) is faster but has no category element. Choose based on your needs.

[[ENC]tbc.net.tw_1.siteconfig.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/12137959/ENC.tbc.net.tw_1.siteconfig.txt)

**Comment by Wangliann** [comment]
I got it ! But the  new Taiwan folder ([tbc.net.tw_0.siteconfig.php](https://github.com/K-vanc/Tempest-EPG-Generator/commit/85f20322ffe9e4fbc62806129eba42e0ddeb3b3f#diff-0080fe80eed6226ca7be1a047633cff1f32834e2e2af4023ac59f10901975cdc) [tbc.net.tw_0.channel.xml](https://github.com/K-vanc/Tempest-EPG-Generator/commit/85f20322ffe9e4fbc62806129eba42e0ddeb3b3f#diff-d037642491e1a4351ca6063a21e186275e076a65843775503136783fd6143443) appears to be empty file~

**Comment by K-vanc** [comment]
it is an upload error by Github. Re-uploaded

**Comment by Wangliann** [comment]
Thanks.
