### ISSUE TITLE
Start-time conversion error found on block 1

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#29]
I am getting a Start-time conversion error found on block 1 and then no show grabbed for tvpassport.com files. Is this an issue with my setup or an an issue with tvpassport?

**Comment by K-vanc** [comment]
Hi,

It looks good here. Tvpassport using unix timestamp as show time/date and it is pretty straight since siteconfig capturing it in a digits-only mode. It may be a particular case. I am on last few days of my vacation so could you please write down below details? I will have a look when I am back.

Your Tempest version?
Your php version?
Your operating system?
Is your system/php date is correct?
Which channel(s) you had issue(with zip code)?
Are you able to visit tvpassport website on the same machine and/or same network since they are blocking some Non US ip adress and vpn connections?

Thanks for your patient
![Screenshot_20230718-234556_Chrome.jpg](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/183fe446-94cb-4bba-a05c-dcc45c111137)

**Comment by stuckinthe** [comment]
I'm using a remote linux server. I tried to ping tvpassport and I didn't get any responses so this is obviously my issue.
