### ISSUE TITLE
tvguide.com[Multi] its working?

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#39]
idk if im du mb but i cant get it run, i do with usa one. i replace files for fresh ones. and able to run usa one. but no multi.

well i get this

![SHOT1051](https://github.com/K-vanc/Tempest-EPG-Generator/assets/79808610/31ee5fee-a642-4515-9f49-ddfff606a101)

i run tempest and i see its not working for colombia but for guatemala and dominic republic yes,  colombia gives error 400

also movistart one from colombia its not working vs argentina its working.

**Comment by K-vanc** [comment]
Hi

each movistart requires ip adress of that country otherwise will not work. So you should have a vpn supports each of that locations and has to switch each time before generating anything. 

For colombia tvguide.com, I tried code " COL|Bogotá " for Colombia/Bogotá and get below result;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/17c01e44-3b2a-4e11-b894-a76304bd3561)

I believe you entered description instead of code. On the list left side of arrow is code and right side is description

Code => Country/City

**Comment by Toei79** [comment]
> Hi
> 
> each movistar requires ip adress of that country otherwise will not work. So you should have a vpn supports each of that locations and has to switch each time before generating anything.
> 
> For colombia tvguide.com, I tried code " COL|Bogotá " for Colombia/Bogotá and get below result;
> 
> ![image](https://user-images.githubusercontent.com/97025515/265320767-606e7054-1629-496b-a6fd-2235b628084d.png)
> 
> I believe you entered description instead of code. On the list left side of arrow is code and right side is description
> 
> Code => Country/City

i see...........thats funny, i mean im usa and argentina one its running fine, but yea ecuador, colombia its not,  i said funny because months ago ,if im no wrong was running without need of vpn from the epg country.

**Comment by K-vanc** [comment]
Every day,  it is getting more harder to get epg :)
