### ISSUE TITLE
Japan EPG siteconfigs is not working

### ISSUE THREAD

**Issue by oldpoem** [K-vanc/Tempest-EPG-Generator#4]
I tried tempest and it looks promising. But I tried 4'siteconfig and only got 1 working (Thailand TrueID).

Tried both bangumi.org and myjcom  , bith returned no shows grabbed. Please look into it.

Also India Tata as well but return can't access to site (possibly geoblock?)

Thanks

**Comment by K-vanc** [comment]
Hi and thanks for using Tempest.

I have checked all your mentioned siteconfigs and didnt find a problem. I believe you have a dns or network problem. It could be also a geoblocking issue but I am also out of Japan and India but able to grab from all as on screenshoots. If you have change try to run again on a different network or with a VPN(on the machine where Tempest runs). Also could you please mention what is your Tempest and PHP versions? 

![image](https://user-images.githubusercontent.com/97025515/208301080-fe01a1da-26ba-4f3d-9fe6-e72fdacdb2d2.png)

![image](https://user-images.githubusercontent.com/97025515/208301126-fc7c3818-7036-471c-b0c7-373b101fbc9a.png)

![image](https://user-images.githubusercontent.com/97025515/208301203-39cec99e-5c3b-4911-b841-86e1e0d29aae.png)

**Comment by oldpoem** [comment]
Thank you for quick reply. I'll try again later. I'm on  tempest latest version with apache/php on my android tablet and android tv box. PHP version is 8.0.6

I don't think it is error from php since I got 1 working  and got different errors with other siteconfigs.

**Comment by K-vanc** [comment]
Hi again. Please keep me updated about issue but in order to be sure, are you running php server on mentioned android devices or they are just Clients to connect a php server running on a windows or linux machine? Because if you are using an android server, %99 this is the problem since there is no official port of php on android yet and available several versions are experimental builds with some incomplete/malfunctional modules. I have also some servers installed on my phone but they are not able to run all siteconfigs and it is impossible to fix from my side. In this case, i can only suggest you to buy a real server device such as 10$ rpi0w which I am still using for my low end performance tests in addition my other devices, and Tempest running pretty good

**Comment by oldpoem** [comment]
I'm using KSWeb pro which is bundled server aplication (apache / php mysql) Have been useing it for over a year for my other project. I have xampp installed on my pc but rarely use it anymore. Would try on it later too. 

Actually I use KSweb pro on my always-on android tv box as webserver / script server and it has been flawless so far.

**Comment by K-vanc** [comment]
One of my user was reported some siteconfigs are not working on KSweb long time ago. I didnt try it but "server for php", "Awebserver" and "Pocket php" android applications are installed on my mobile and each of them are able run and cannot run different siteconfigs. Tempest using lots of modules and hundreds of different commands for regular operations. Since none of them completely work same as linux or windows php, noone can guarantee which siteconfig will run and which not. Unfortunately, i have no support for experimental servers. If an official port of php is released for android, for sure i will make adjustments in case of need but currently I will close the issue when you test on xammp and confirm it works.

**Comment by K-vanc** [comment]
I have installed KSweb to reproduce issue and some kind of server error(belongs to Ksweb) happened on bangumi and worked fine with myjcom. When i checked the apache log, i noticed some kind of timeout achieved and script aborted. If you know some setting to adjust that timeout maybe it can help you but as I said there is nothing to be fixed from my side.
![Screenshot_20221218-201821_Chrome](https://user-images.githubusercontent.com/97025515/208311073-c5c3cf3d-2441-45e3-b80b-e08192b813a6.jpg)
![Screenshot_20221218-202338_KSWEB](https://user-images.githubusercontent.com/97025515/208311076-32b8cda1-9cbc-4525-88a1-85f8e0308f4a.jpg)
![Screenshot_20221218-201927_Chrome](https://user-images.githubusercontent.com/97025515/208311077-629fe71e-ec19-4699-8332-b90707598d0f.jpg)

**Comment by oldpoem** [comment]
Tested on XAMPP / Windows 10.  Same results. 

![Screenshot_2022-12-22-03-39-23](https://user-images.githubusercontent.com/20328943/208998968-325cc8d6-9ad0-4d30-bfa1-b24e06608087.jpg)

**Comment by oldpoem** [comment]
After compare the results, I found out that my downloaded myjcom siteconfig got corrupted (all siteid is different from your results). I downloaded myjcom siteconfig again and it works now. Not sure how it got corrupted , maybe a bug?

For tataplay it's still not workingg.

**Comment by K-vanc** [comment]
Hi again. Corruption is not the correct word but let's say faulty site_id. I checked channel creation of myjcom and noticed that they made a small change on their syntax which caused partial grabbing of site_ids. Revised siteconfig which creates correct site_ids on channel generation, is available in Japan folder.

For Tataplay, you are receiving a "403 FORBIDDEN" error which means server is understanding your request correctly but not allowing you to pass from its firewall. Your external ip or your country ip range(I dont know in which country you are) may be blocked by server. I believe if you use a vpn or set a proxy(from Tempest Configurator), you will get data. If you are using dynamic ip, try again after restarting your router which will assing you a new external ip

![image](https://user-images.githubusercontent.com/97025515/209057099-230c8f9a-05ad-4764-a3c9-c3b6d16435bd.png)

**Comment by oldpoem** [comment]
BTW i tried bangumi.org  siteconfig for one channel (BS Japanet which is siteid 30).  And found out that it gabbed next channel which is BS yoshimoto (siteid 31).  Right now I did a workaround by grabbing siteid 29 to use for BS Japanet instead.  

Not sure qbout other channels since all of it is available in myjcom channels.xml  except BS Japanet.

**Comment by K-vanc** [comment]
well, I am trying to help but to be honest, your feedbacks are mostly useless.. That siteconfig is already cryptic for me since channel names in Japanese so I have no idea about which channel is BS Japanet and also there is no site_id as 30 in channel list. If possible please write name of channel as it shown in channel list. It could be changed till the time I did that siteconfig. I am not personelly using +350 shared siteconfigs here and i cannot know which one is changed unless a user reports me. I will have a full review on bangumi siteconfig

**Comment by K-vanc** [comment]
Ok, I have checked bangumi and everything is ok. Only you need to rechannel create. I think this is the channel you mentioned;

site="bangumi.org_0" site_id="bs?|##| ＢＳＪａｐａｎｅｘｔ||29" xmltv_id="ＢＳＪａｐａｎｅｘｔ">ＢＳＪａｐａｎｅｘｔ</channel>

So that last number is an indicated I used for position of channel in source code. Website removed some channels since the date I made/shared siteconfig. When you create new channel list, it will be 29 as above

**Comment by oldpoem** [comment]
OK seem like my bad on this one. I should generate new channels list before report anything like this.  I'm kinda new to this stuff.  Only use webgrabplus before.

Sorry to bother with noob questions. Appreciate the effort and dedication.

**Comment by K-vanc** [comment]
You are welcome. The channel lists that I shared, are just for generic information. %99 of the siteconfigs supports dynamic changes and will update channel list with new data unless there is a major change on website's structure. In this case, you can freely report to me so I will make necessary modifications in my the soonest availability.  Always keep in mind to start with channel creation when you  download a new siteconfig since some websites are changing site_ids even weekly.

As an old team member of webgrab+, I have developed/released Tempest to stop people using that prehistoric tool and let them have better/faster epg data for free instead of mandatory donations which mean taxes.. So enjoy and feel free to ask anything but if you give me more clear details, i can reply faster :)
