### ISSUE TITLE
Dstv/nga - No Channel Block Found

### ISSUE THREAD

**Issue by naijaping** [K-vanc/Tempest-EPG-Generator#46]
Hiya,
I was trying to create channels for Dstv/Nigeria but unfortunately it keeps coming back as No Channel Block Found.

I used [ENC][EX]dstv.com_0.siteconfig.php  found in multi nation. what am I doing wrong please.

Anyone have Dstv/Nigeria to please share with me?

Thanks

**Comment by K-vanc** [comment]
hi @naijaping 

First, you had better to use one of [ENC][EX]dstv.com_1 or 2. Revision 0 is outdated but i am not removing because some days, it is still working. If you planning to use only for Nigeria(or any single country), use revision 1 because it will grab faster.

Then for channel creation, you need to input country code of Nigeria as user key. It is already explained below link with pictures but probably you didnt see it and asked in everywhere possible :)

 https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/Multi%20Nation/Info%20for%20dstv_com.md

if you run channel creation without user key, it will create a txt file in siteconfig folder as "dstv_country_codes". You can check it for the code of country you want then you have to type it on channel creation. Code of Nigeria is currently nga . I checked and it created 171 channels so no problem with siteconfig

**Comment by naijaping** [comment]
Many thanks @K-vanc , all sorted after using [ENC][EX]dstv.com_2.

Keep up the good work .

Regards

**Comment by K-vanc** [comment]
you are welcome and enjoy Tempest
