### ISSUE TITLE
Siteconfig Request

### ISSUE THREAD

**Issue by dbmtech** [K-vanc/Tempest-EPG-Generator#47]
Hi K-vanc

Is it possible to make siteconfig from application (Android application)? This app is the official TV Guide App for India.

App Link from playstore - 
https://play.google.com/store/apps/details?id=com.whatsonindia&hl=en_IN&gl=US

Thanks

**Comment by K-vanc** [comment]
Hi @dbmtech ;

Since those applications are also connecting a server for fetching data, theoretically it is possible and I did many times such things for Tempest and before Tempest. But in practical, it is not the same thing as making siteconfig for websites since inspection/debugging tools are very limited and useless for mobile devices and for some cases it is very difficult(or almost impossible) to identify their web sources without installing several software into mobile and another supporting pc, trying to sniff application, if application using tsl(which %99 of them is using) tyring to decrypt data over pcaps etc. So it is very time and effort taking process and there is no guarantee at the end that if it will work or not. Because of this, i will not take your wish as simple siteconfig request but a question and will add it into my to-do list. But do not expect something soon since currently and upcoming weeks, I dont/wont have enough free time to make such setup and try.

Instead of google play link, if you can identify any their data link related with epg, we can go much more faster.

**Comment by dbmtech** [comment]
ok

**Comment by dbmtech** [comment]
I checked in mobile application .. its fetching data from site "https://services.whatsonindia.com/". but its saying access is denied while opening site. also its showing required api key in app. 
like for fetching program details
http://services.whatsonindia.com/recoStar/recoStarHost.svc/ProgramFullDetails?apikey=2f9f705a38307c470e3a819ac1f6df7a7fa0ffbc&responseformat=json&responselanguage=english&pageno=1&scheduleid=

**Comment by K-vanc** [comment]
I will have a look soon. That key probably one-time-use only. Also please dont share such links to public here. You may privately send me by mail

**Comment by dbmtech** [comment]
ok

**Comment by K-vanc** [comment]
hi @dbmtech 

How can you login or register? I couldnt find any registration also when I click login, it redirects to home page again

**Comment by dbmtech** [comment]
Click on preference or login

There are 3 methods
1st sign in whatson account (first sign up needed through any mail)
2nd by sign with google account
3rd by sign in with Facebook .



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by K-vanc** [comment]
when i click to preference, only login page is coming and when i click to login, it redirects me back to home page so there is no option as you mentioned. maybe it is geo-blocked but seems like my vpn doensnt have india server.. Anyway, I did channel creation and epg part(not perfect as I want but working) but need detail pages for description etc. The link you send me definitely not working. Are you sure about it especially api key and how you get it?

**Comment by dbmtech** [comment]
I decoded app through apk editor where i find api parameters.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by K-vanc** [comment]
hmm ok. Probably they are false or belongs to some other place. Anyway, I will try to find a way

**Comment by dbmtech** [comment]
Ok.. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by K-vanc** [comment]
hi @dbmtech 

I tried also with India VPN but didn't make any difference on login issue. Later on I checked google play reviews of app and it seems this is a known and not yet fixed issue since 2020 that there are hundreds of reviews telling as login button not working. So i cannot go further through app. Could you please copy the thing you see related with urls etc. on that editor into a txt file and send me with mail( tempestepg@gmail.com )? Maybe I can dig a little more to get descriptions.

**Comment by dbmtech** [comment]
kindly check mail

**Comment by K-vanc** [comment]
It is in India folder as English and Hindi versions. Not perfect(for me) but working good and cannot be better than this without login

**Comment by dbmtech** [comment]
thanks.. working good..

**Comment by K-vanc** [comment]
Enjoy.. You also contributed to victory :)

**Comment by dbmtech** [comment]
👍

**Comment by dbmtech** [comment]
Hi, its suddenly stopped working. kindly check whenever you have time. If login not working even with using VPN, you can try VPN along with app "Mock Locations (fake GPS path)". May be geo location blocked app can be open with the help of this app. I am providing app link here.
https://play.google.com/store/apps/details?id=ru.gavrikov.mocklocations&hl=en&gl=US&pli=1

Thanks

**Comment by K-vanc** [comment]
this is the nature of siteconfigs, sometimes they work and sometimes suddenly stop. No need to be so happy when they work or panic when they stop.. In the app it says service is unavailable and showing no channel or epg. Also it seems, application is not foundable in google play(at least for me) anymore. Sorry but I will not install any weird application into my mobile just to make some siteconfig work..

Are you able to see data in app?  Maybe they shut down the app completely or it is a temporary service issue or they geo-block which it is not always possible to bypass with VPN

**Comment by dbmtech** [comment]
Showing data in pre installed app but app not showing in playstore now.

**Comment by K-vanc** [comment]
I think they are planing to close down apps. Anyway, if you are seeing data in app, you should also able to grab if they didnt change the urls. Can you mail me again a file what you see with apk analyser

**Comment by dbmtech** [comment]
Sorry for late reply, Yeah you are right. They removed app from playstore and now app is not showing any data.
