### ISSUE TITLE
Bein sports & Entertainment

### ISSUE THREAD

**Issue by islamsabry2008** [K-vanc/Tempest-EPG-Generator#51]
Please 
can you fix the Ids with the new ones?

**Comment by K-vanc** [comment]
Hi, I cannot do that but you can do by using Channel Generator option;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/f0d08519-413c-48e6-b93c-178686b020dc)

and clicking Generate button

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/a7a1107f-0dad-42d5-9cb5-517a0d86e254)

In order to take effect, you need to delete old channels from your configuration and add new ones
