### ISSUE TITLE
KSA

### ISSUE THREAD

**Issue by islamsabry2008** [K-vanc/Tempest-EPG-Generator#54]
Hi my friend
 mobily and jawwy in KSA not works at all
Thank you so much in advance

**Comment by K-vanc** [comment]
Hi,

They both work at all but you need to check remarks for requirements of siteconfigs before raising issue.. For jawwy it is written as you need to increase php memory to something as minimum 400M so you need to change it from your php.ini and restart php server;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/8061392d-0bef-4dcd-af6e-5b69bc2c0ac8)

and result below after proper setting;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/cdd4446c-e7f7-4300-80c2-f96ee4de2c57)

and for tv.mobily, I noticed a typo in url and updated both en and ar versions. it is written as Suitable IP adress required. I dont have KSA IP or VPN has such IP so I tested with a free Dubai proxy and it also works now.(I couldnt attach screenshot because free proxy worked only once when I didnt screenshot and blocked me on my next attempt)

**Comment by islamsabry2008** [comment]
mobily now is perfect but jawwy still nothing

**Comment by K-vanc** [comment]
Did you increase memory in php.ini?
Did you restart your php server after editing php.ini?
Do you have plenty of memory in your device? 400M means 400mb of free ram will be occupied for php
This 400M I wrote is Just estimation. On my screenshot it used ~340mb. It may be a little more or A little less based on operating system and php server. You may still need some bigger value than 400M on your device. If you did all above steps correctly, try again with a higher value such as 500M(or 1000M to guarantee) to see if it will work.

**Comment by islamsabry2008** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/1075689/8fe4a506-b586-42a5-80d3-05e390899255)

**Comment by K-vanc** [comment]
Hi,

Your setting is correct but I have concerns about if it is effective. Can you please create a test.php script near tempest.php add below line in it;

`<?php echo ini_get('memory_limit'); ?>`

When you call test.php, it will print effective memory setting into your screen. If it is showing 1024M, then I will start digging out for another but I think you have multiple phps and editing not working one.

By the way, are you getting any url error while trying to grab? and can you write which channel(s) you have tried? There are many channels but not all of them has epg so maybe it is all working properly but you are running channels without epg

**Comment by islamsabry2008** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/1075689/7f599fd7-f119-4dd7-9d02-7f3861b11f64)
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/1075689/58cb1257-3998-4b24-aae3-a06d19250df8)

**Comment by K-vanc** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/d99b6d94-0874-4dce-aa6a-b2748a3bd994)

I tested the latest Tempest release version with the encrypted siteconfig downloaded from repo. If you check the difference on peak memory  as mine +300mb and yours +155mb, it seems website is giving you another response than me. There are 2 possibilities as;

* First, it is geo-blocking you and giving you a dummy response without any show. Can you try to check from your browser if you can visit web.jawwy.tv website?
* Second, if we consider 155mb response is too much for a dummy, it is not geo-blocking but content(and possibly channels) are changing based on geo-location. Did you try to generate fresh channel list? Please check if you will notice any difference on number of channels, names etc. Channel Ids on my list may not be applicable for your country

**Comment by islamsabry2008** [comment]
the solution is 5 days to grab or less 
thanks for your work my friend

**Comment by K-vanc** [comment]
Welcome but I dont understand how it worked for you :)  How many days you were grabbing before? It is strange because There is no urldate setting on that siteconfig which will effect url request. API is sending all data of each channel upto 10days. Anyway, still good to hear works also for you now

**Comment by islamsabry2008** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/1075689/a29fdbe6-4a4c-496d-965b-f933839052fa)
I know 
this grab for 6 days

**Comment by islamsabry2008** [comment]
Sadly
It not works anymore now

**Comment by K-vanc** [comment]
Will we continue to repeat this "NOT WORKING-NO, IT IS WORKING" periodically??

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/a82efc40-f5be-4023-91cb-00518dd1678f)

Increase memory and run it in timespan 0. It is set to grab all available days by default..

**Comment by islamsabry2008** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/1075689/bc38ce83-6543-468b-b5b8-625c6e9d9986)
I swear it is not working
all works fine-osn+shasha+mobily...etc all fine 
exept jawwy
I also tried on new installed windows 10 and ubuntu too
and I live in Middle East
Anyway thank you so mucch for your work

**Comment by K-vanc** [comment]
You are completing operation with no show so it is not a memory issue for you. there may be some other reason that it is not working for you. In this days, most of the websites are adding extra security layers to stop grabbing, headless machine access etc. Your ip adress(external which is same for all your devices on the same network) may be temporarily or permanently blocked by server if you have been blacklisted. I am using that siteconfing only for to check when you ask as it is not working. If you have a vpn with suitable location, try again while vpn is on on grabbing machine.

**Comment by K-vanc** [comment]
I have checked our previous discussions on this topic. I have already mentioned you about some kind of geo-blocking. On the screenshots, your peak memory usage is around 300MB when it is working and 150MB when it is not working for you. That peak memory is directly related with server's response and 150Mb difference is a huge difference so for sure website is giving you another response when it stop working than what I receive always. I also asked you to re-channel create but you didnt write anything about it.  This difference may be related with you are blacklisted and getting a dummy reply with no shows or server is evaluating your location to some other place and giving you data of some different country/location but since your selected channels are for different country, your grabbing ends with 0 show.

**Comment by islamsabry2008** [comment]
fix rotana please

**Comment by K-vanc** [comment]
> fix rotana please

Updated. Replace your existing channels and with new ones since they also changed channel ids

**Comment by islamsabry2008** [comment]
It grabs nothing

**Comment by K-vanc** [comment]
and done

**Comment by islamsabry2008** [comment]
Hi my friend
thank you for your great work
I think /KSA/tv.mobily.com.sa is block for now it gives
Start-time conversion error found on block 1...

**Comment by K-vanc** [comment]
they revised their data structure. You can use updated siteconfigs

**Comment by islamsabry2008** [comment]
Hi my friend
I think there is a problem in Jawwy.tv

**Comment by islamsabry2008** [comment]
Please my friend
Sat.tv is not getting the Arabic EPG ,Its always English

**Comment by K-vanc** [comment]
siteconfigs were updated

**Comment by islamsabry2008** [comment]
please 
will you check gobox in KSA?
