### ISSUE TITLE
Update config mewatch.sg

### ISSUE THREAD

**Issue by febiferdiansyah** [K-vanc/Tempest-EPG-Generator#55]
Hi, Singapore folder `mewatch.sg` channel logo is not displayed..

**Comment by K-vanc** [comment]
Hi, it is grabbing channel logos and logo urls are fine..

Your low-end iptv player, at least, shall be able to convert "`&amp`;" into "&" because it is an escape character for xml and it shall be encoded as "`&amp;`" for being used properly..

You may contact forum of your low-end iptv player.

`<channel id="Channel 5">
    <display-name lang="en">Channel 5</display-name>
    <icon src="https://production.togglestatic.com/shain/v1/dataservice/ResizeImage/$value?Format=%27png%27&amp;Quality=85&amp;ImageId=%271776036%27&amp;EntityType=%27Item%27&amp;EntityId=%2797098%27&amp;Width=114&amp;Height=114&amp;device=%27web_browser%27&amp;subscriptions=%27Anonymous%27&amp;segmentationTags=%27all%27&amp;ResizeAction=%27fill%27&amp;HorizontalAlignment=%27center%27&amp;VerticalAlignment=%27top%27"/>
  </channel>
  <channel id="Channel 8">
    <display-name lang="en">Channel 8</display-name>
    <icon src="https://production.togglestatic.com/shain/v1/dataservice/ResizeImage/$value?Format=%27png%27&amp;Quality=85&amp;ImageId=%271776034%27&amp;EntityType=%27Item%27&amp;EntityId=%2797104%27&amp;Width=114&amp;Height=114&amp;device=%27web_browser%27&amp;subscriptions=%27Anonymous%27&amp;segmentationTags=%27all%27&amp;ResizeAction=%27fill%27&amp;HorizontalAlignment=%27center%27&amp;VerticalAlignment=%27top%27"/>
  </channel>
  <channel id="Channel U">
    <display-name lang="en">Channel U</display-name>
    <icon src="https://production.togglestatic.com/shain/v1/dataservice/ResizeImage/$value?Format=%27png%27&amp;Quality=85&amp;ImageId=%272261554%27&amp;EntityType=%27Item%27&amp;EntityId=%2797129%27&amp;Width=114&amp;Height=114&amp;device=%27web_browser%27&amp;subscriptions=%27Anonymous%27&amp;segmentationTags=%27all%27&amp;ResizeAction=%27fill%27&amp;HorizontalAlignment=%27center%27&amp;VerticalAlignment=%27top%27"/>
  </channel>`
