### ISSUE TITLE
Req Sweden schedule

### ISSUE THREAD

**Issue by indraprawiratamaharlis** [K-vanc/Tempest-EPG-Generator#60]
Hi, good morning, can you add the schedule from the website? Thank you 🥰https://www.tv4play.se/kanaler

**Comment by K-vanc** [comment]
Hi, it didn't look like to me as a proper epg source. There are only 5 shows available for each channel with minimum information(start/stop date and title). Not possible to request more days or more epg content. Is there any special reason that why you need this website? Because all these channels are available in other Sweden siteconfigs with proper data. You only need to rechannel create if you didnt find those channels

**Comment by indraprawiratamaharlis** [comment]
Thank you, I have found the channel I was looking for, apparently I need to add the siteid manually, because when I generated the channel I was looking for it didn't exist...

**Comment by K-vanc** [comment]
can you please write siteconfig name and channel name/id you mentioned then I can check if it exists or a siteconfig error. Sometimes websites are removing channels from their epg list but for some more time they continue to provide unlisted epg or something may be changed on website so siteconfig cannot grab that channel anymore
