### ISSUE TITLE
[ENC][EX]directv.com.co_0 not work 

### ISSUE THREAD

**Issue by maurioski** [K-vanc/Tempest-EPG-Generator#70]
seeveraly monthe this guide dont work, don't extract any channel, or update.

**Comment by K-vanc** [comment]
I know.., my vpn is not passing geo-blocking currently. I will deal with it after repo maintenance

**Comment by Toei79** [comment]
theres some from usa not working online ones fixed.io, online.tivo, app.plex

theres one streamtvguides, im guessing dont need user key parameter, if its like that , its dont generate, permissions are ok

**Comment by K-vanc** [comment]
ok guys, thanks, that's why I am doing repo maintenance.. No need to write one by one. I am going in alphabetic order of folders and in France now. I am fixing or noting if something more is needed..

**Comment by K-vanc** [comment]
guys, I will take care of all directv siteconfigs when I finish maintenance as they did several changes and added new security layer to all. Cannot display website from my work network.

**Comment by K-vanc** [comment]
Well, repo maintenance is over and will check and try to fix all directv + tvlisting.zap2it siteconfigs according to my notes as not working.

@Toei79 

app.plex and streamtvguides siteconfigs are already fixed
For flixed.io & online.tivo, I made small corrections on xmltv elements but siteconfigs are working fine as it is. So if you are having trouble with those, please  send me some more details with log, channel ids, your config.xml file etc. They could be also block your ip adress since some siteconfigs such as flixed, tvpassport, tvtv.us are increased their security level and ttemporarily ban you in case of multiple requests in a short time

**Comment by Toei79** [comment]
thanks! like always

i see, how many days in between requests? just to be safe. 


im trying do a script that run every x days  ,  that make me updated the 60 files that run  on site_config folder, like check Siteconfigs folder and just replaced ones on folder site_config  without add more files , im been googling and im going to keep checking no figure out yet. 

maybe do one by one on script.

**Comment by K-vanc** [comment]
Hi,

zap2it updated and working again. For siteconfigs, there is no interval. Now all working but noone knows how long they will stay working. I have some siteconfigs that working since 4 years unchanged and i know some that website is changing more or less every few weeks. I checked all siteconfigs during maintenance but probably I will not do it again.. So if something is broken, it will be only updated when someone reports it 

You can use siteconfig updater periodically like once a month etc then has to some code with unzip then copy/paste several files with hardcoded paths since country name etc will not change.

BTW, directv in progress. USA done but still testing then I will check Colombia

**Comment by K-vanc** [comment]
Hi @maurioski 

I finally checked yesterday. Siteconfig is still fine but they started use some kind of security challenge similar to cloudflare and it is probably not possible to grab now since even if I find a way to bypass it, probably, will not publish my solution. So you can consider as there is no directv south america siteconfig till they stop using that additional layer(for sure they will stop or reduce security level after sometime since these kind of protections are expensive) but at the moment, game is over
