### ISSUE TITLE
UEA: etisalat-tv.com

### ISSUE THREAD

**Issue by febiferdiansyah** [K-vanc/Tempest-EPG-Generator#72]
Is the schedule taken correct, because in my schedule there is no match at all. i tried to shift the regions and time zones, but also did not find the right schedule. if you are free maybe you can try to check it...

**Comment by K-vanc** [comment]
??????????????

**Comment by K-vanc** [comment]
This siteconfig using their android app as source. All included channels exist for almost all countries of MENA region but channel schedules are different from each other for each country. Since there is no problem on grabbed data's date/time, i dont know if it is physcially matching with TV or not since I cannot verify them on TV. If you have any comparison, please share so I can have a look.
