### ISSUE TITLE
Program description is not available

### ISSUE THREAD

**Issue by otava5** [K-vanc/Tempest-EPG-Generator#84]
Hello.
Thanks in advance for the perfect addon.
I have questions:
1. I don't see the "**_program description_**" from the generated CZ programs or from any xml.
2. If I want to merge 2 generated files using "xmlmerge" under Linux and the file contains the "**&**" character, then the resulting merged file is corrupt (defective).

- Ubuntu 22
- Apache
- PHP 8.1
- Tempest 1.6.1.0

thanks for the anwers

**Comment by K-vanc** [comment]
Hi,

1) Can you please write name of siteconfig(s) and channel(s) that you cannot get description? I tried random channels on magio and o2 siteconfigs but descriptions are all there. 

2) I dont know what is that progrom and never used it. Generated xml files by Tempest are all valid as per xml schema and you can also verify it is correctness by online xml validators. if there would be a problem on xml schema, you cannot open/display to file and your player cannot get any epg data also. "&" character is being escaped when it is attribute of an xml tag with "&amp;" format and can be safely used when it is as data (out of xml tag). Probably the software you are using, doesn't know how to escape or convert that char(or maybe more chars since & is not only the one to be escaped). Sorry but cannot help you more about this.

**Comment by otava5** [comment]
I miss this
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/26667859/14eb4dca-7a89-4fa3-9dc7-952208501e65)

**Comment by K-vanc** [comment]
Are you sure that you are running latest updated siteconfigs? I dont remember the names but I remember i fixed several siteconfig in Czech folder that running partially such as missing description etc. Your configuration seems ok. If also no error reported when you running Tempest about some missing module etc, there shouldnt be any problem. All the credits data etc are coming from the same place with description. I attached txt file with what I grabbed with latest siteconfigs

[test.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/14021067/test.txt)

Are you running  any other software for merging/editing xml files? I can only suggest to delete your config.xml, siteconfigs, redownload siteconfigs, rechannel create and create fresh config.xml with newly generated channels from newly downloaded siteconfigs

**Comment by otava5** [comment]
On the contrary, when I started the service on free hosting, I have a description here...
Any advice on what I'm missing in apache/ubuntu? Is it possible to make a debug log where I can read it?

**Comment by K-vanc** [comment]
?? Did you forget to attach something or photo ??

**Comment by otava5** [comment]
Please have a look at the attached php statement, but with the parameter "error_reporting(-1)" for a statement of all errors and at the same time the log output of Tempest.
"error_reporting(1)" - didn't show anything....
[php_error-1.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/14035042/php_error-1.txt)

```
[                   ]
[                   ]-------------------------------------
[                   ]        Tempest EPG Generator
[                   ]
[                   ]   The Most Advanced Programmable
[                   ]       GUI XMLTV EPG Generator
[                   ]     by Kivanc Altug aka "Kvanc"
[                   ]-------------------------------------
[                   ]
[24-01-2024 08:38:36] Tempest Version : rv1.6.1.0-2401220703
[24-01-2024 08:38:36] System Info : Linux NAS 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64
[24-01-2024 08:38:36] PHP Version : 8.1.2-1ubuntu2.14
[24-01-2024 08:38:36] Server Info : Command Line Interface (Cli)
[24-01-2024 08:38:36] Initializing...
[24-01-2024 08:38:36] Checking required modules...
[24-01-2024 08:38:36] Time converter enabled...
[24-01-2024 08:38:36] epg.xml generated...
[24-01-2024 08:38:36] Grabbing started for 2 days
[                   ]
[24-01-2024 08:38:36] (1/1) Site: [ENC][EX]o2tv.cz_0
[24-01-2024 08:38:36] Channel id: PrimaStar
[24-01-2024 08:38:36] Xmltv id: Prima Star
[24-01-2024 08:38:41] 48 shows grabbed in 4.93 seconds
[                   ]
[24-01-2024 08:38:41] Grabbing completed...
[24-01-2024 08:38:41] 48 shows grabbed in 4.93 seconds
[     Completed     ]
[24-01-2024 08:38:41] Tempest Overall Memory Usage: 4435KB
[24-01-2024 08:38:41] Tempest Peak Memory Usage: 11274KB
```
Thnx very

**Comment by otava5** [comment]
ok then let me know if i should upgrade to 8.2 or 8.3 to solve the problem ;-)

**Comment by K-vanc** [comment]
i am trying to understand what is happening. For some reason 1 of my code block related with description returns empty in php8 for ENC siteconfigs. Probably it is happening on all ENC siteconfigs but strange that noone metnioned about it yet except you. Probably only u are using php8. Anyway, I will let you know when I figure it out. Another siteconfig update or Tempest update or both may be required for it...

**Comment by K-vanc** [comment]
Hi @otava5 

I pushed the patch. Please click Tempest Update and grab again your configuration to check if all ok

**Comment by K-vanc** [comment]
Good that issue resolve.

this is not about siteconfig or website. It is a combined issue related with php8 + openssl + curl libraries . There is nothing I can help on that. you can try to update/downgrade php / curl / openssl till you find a working combination or you can wait for website to fix problem on their ssl certificate. Unfortunately, php8 is not proceeding when a certificate issue found unlike php7. It is telling you that website's ssl key lenght is sorter than required for the chipper they used.  In both openssl and curl groups, they are telling that they fixed the issue and asking to check with other library but there is no clear info as which library versions are ok. that's why still i am mainly using php 7.4 as the most stable version

**Comment by otava5** [comment]
This worked for me
[https://github.com/curl/curl/issues/9186#issuecomment-1493325591](url)
Thanks for the great work sir @K-vanc

**Comment by K-vanc** [comment]
Good to hear. Long time ago, i tried to implement some switches for this in Tempest but 1 fixed, broke the others so stopped wasting my time with it.

I know that reducing tsl level may work sometimes as already shared it in another old issue ( https://github.com/K-vanc/Tempest-EPG-Generator/issues/31#issuecomment-1651009781 ) but i personely not suggesting it since it is causing major network security issues. This is not a solution that i want to use on my daily pc but it is your pc
