### ISSUE TITLE
XML via url

### ISSUE THREAD

**Issue by SirdLay** [K-vanc/Tempest-EPG-Generator#90]
## Issue Type

Please choose your issue type

[ Request ]

A feature to share XML via url

**Comment by K-vanc** [comment]
Hi, could you please explain a bit more about what you asked as feature? Because if i understood correct, "sharing generated file via an url" can be done via a hosting service so how do you expect me to do it through Tempest?

**Comment by SirdLay** [comment]
hey Thanks for the reply. I was hosting this on directadmin. All I had to do was create rewrite rule to access files from epg folder.
Since I'm not a tech guy, required help from chatGPT.  

Another one doubt, is it possible to set a cron job to generate EPG. Your Help is much appreciated. 
Btw thanks for this awesome project

**Comment by K-vanc** [comment]
Good to hear. Yes cron or any other scheduled tasks can be performed via cli commands. All you need to call tempest.php file with parameters you need through php installed on your pc/system;

php /path/of/tempest.php engine=Generate (tempconfig=name.config.xml) (createxmlgz=on) (createinvxmlgz=on)

Ones is parantheses are optional so you can delete if u dont need or remove parantheses if u need. If you are using default tempest.config.xml, then u dont need tempconfig parameter otherwise modify it with your config name. You can crontab above command line with the running intervals you need. There are several examples for usage of cli commands which for grabbing Epg, channel creating and updating tempest in TempestWIKI.pdf and in some other closed issues.
