### ISSUE TITLE
directTv  from latin america?

### ISSUE THREAD

**Issue by maurioski** [K-vanc/Tempest-EPG-Generator#93]
still don't work any of dtv files.

https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/Colombia/%5BENC%5D%5BEX%5Ddirectv.com.co_0.siteconfig.php

**Comment by K-vanc** [comment]
hi @maurioski

For South America, it is still not working and will continue not to work as I already explained you here;

https://github.com/K-vanc/Tempest-EPG-Generator/issues/70#issuecomment-1928744001

Because of this security layer, currently it is not possible to bypass for me. If you believe it is possible, Siteconfig Maker is open for everyone
