### ISSUE TITLE
Setup siteconfig

### ISSUE THREAD

**Issue by NHKRoku** [K-vanc/Tempest-EPG-Generator#99]
Hi,it's me again
I create this issue to ask you some config in siteconfig
I have a xml source that have a catch-up source
So can I ask you that can i setup catchup source in tempest?
Hope your answers.

**Comment by K-vanc** [comment]
sorry but your question is not so clear to me. Do you want to use your local xml file as source of epg ? If yes, you need to make your own siteconfig and your url will start with file command and followed by absolute path of your xml file so;

file:///C://Your/xml/file/path/source.xml

But, you cannot grab for old days. Dates older than today will be deleted automatically. Instead of this you can make your own catch-up included epg file by using Fusion module in Configurator. Enable fusion and set level to max days you want to store as catch-up. In each run, Tempest will preserve available old days and grab new days as well into the same xml file. Within couple of days(based on your level value), you will have full catch-up data + new day(s) data. Tempest will continue to update catch-up data by deleting excess days and linking newly grabbed days. Also I recommend everyone to use fusion on level 0 so it will preserve available current data in case of a failure on new grab
